disabled_rules: # rule identifiers to exclude from runn
  - line_length
  - todo
  - redundant_string_enum_value
  - trailing whitespace
  - identifier_name
  - type_body_length
  - file_length
  - function_body_length
  - nesting
  - opening_brace
  - trailing_newline
# rules that have both warning and error levelscan se
# implicitly
line_length:120
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 #error
#or they can set both explicitly
file_length:
  warning:500
  error:1200
  
trailing_comma:
  mandatory_comma: false
# naming rules can set warnings/errors for min_length a# additionally they can setexcluded names
type_name:
  min_length: 2#only warning
  max_length: # warning and error
    warning:40
    error:50
  excluded: iPhone # excluded via string
identifier_name:
  min_length: #only min_length
    warning:2
    error: 2#onlyerror
  excluded:
    - URL
    - key
    - lhs
    - rhs
reporter: "xcode"
excluded
    Pods
